site_name: "Neo4J API"
site_description: "A Neo4j API in Python with FastAPI."
site_url: "https://pawamoy.github.io/neo4j-api"
repo_url: "https://github.com/pawamoy/neo4j-api"
repo_name: "pawamoy/neo4j-api"

nav:
  - Overview: index.md
  - API Reference:
    - cli.py: reference/cli.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/neo4j_api
